const nodemailer = require("nodemailer");

let transporter;

// Lazy initialization of transporter to allow async Ethereal account creation
const getTransporter = async () => {
    if (transporter) return transporter;

    const user = process.env.EMAIL_USER;
    const pass = process.env.EMAIL_PASS;

    if (user && pass) {
        transporter = nodemailer.createTransport({
            service: "gmail",
            auth: { user, pass }
        });
    } else {
        console.log("⚠️ EMAIL_USER/EMAIL_PASS not configured in .env. Generating temporary Ethereal test account...");
        const testAccount = await nodemailer.createTestAccount();
        transporter = nodemailer.createTransport({
            host: testAccount.smtp.host,
            port: testAccount.smtp.port,
            secure: testAccount.smtp.secure,
            auth: {
                user: testAccount.user,
                pass: testAccount.pass
            }
        });
    }
    return transporter;
};

const sendRegistrationEmail = async (email, username) => {
    try {
        const client = await getTransporter();
        const fromAddress = process.env.EMAIL_USER || '"Banking System" <no-reply@bank.com>';
        
        const mailOptions = {
            from: fromAddress,
            to: email,
            subject: "Welcome to Our Banking System!",
            html: `
                <div style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
                    <h1 style="color: #4A90E2;">Welcome to the Banking System, ${username}!</h1>
                    <p>Thank you for registering with us. Your account has been successfully created.</p>
                    <p style="font-size: 12px; color: #777;">This is a test notification generated by Nodemailer.</p>
                </div>
            `
        };

        const info = await client.sendMail(mailOptions);
        console.log(`[Email Service] Email sent successfully: ${info.messageId}`);
        
        // Log the preview URL if we're using the Ethereal test account
        const previewUrl = nodemailer.getTestMessageUrl(info);
        if (previewUrl) {
            console.log(`✉️ Preview test email here: ${previewUrl}`);
        }
        return true;
    } catch (error) {
        console.error(`[Email Service Error] Failed to send email: ${error.message}`);
        return false;
    }
};

module.exports = {
    sendRegistrationEmail
};
